language: python

python:
  - "3.10"

# Only run on push and pull request events
branches:
  only:
    - main

# Environment variables
env:
  global:
    - CODECOV_TOKEN=feeefeld-baad-4dba-a89a-6c5861823c5e

# Install dependencies
install:
  - pip install -r requirements.txt

# Run linting and tests
script:
  - pytest --cov app

# After success
after_success:
  - codecov

# Node.js setup
before_install:
  - nvm install 12
  - nvm use 12

# Cache dependencies
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.npm

# Notifications
notifications:
  email:
    recipients:
      - 9980056379Skanda@gmail.com
    on_success: always
    on_failure: always
